'use client';

import { useState, useMemo, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { getBreaches, getBorrowerById, getDealByBorrowerId, getBreachesByBorrowerId } from '@/lib/data';
import type { Breach, Borrower, Deal } from '@/lib/types';
import PageHeader from '@/components/PageHeader';
import SeverityBadge from '@/components/SeverityBadge';
import BreachReasoningPanel from '@/components/BreachReasoningPanel';
import BreachHistoryTimeline from '@/components/BreachHistoryTimeline';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmt(value: number, unit: string): string {
  const r = Math.round(value * 100) / 100;
  if (unit === '$M') return `$${r}M`;
  if (unit === '%') return `${r}%`;
  return `${r}x`;
}

function operatorLabel(op: string): string {
  return op === '<=' ? '≤' : '≥';
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function fmtDateShort(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-[10px] font-bold uppercase tracking-widest mb-3" style={{ color: '#94a3b8' }}>
      {children}
    </div>
  );
}

function Divider() {
  return <div style={{ borderTop: '1px solid #e2e8f0', margin: '20px 0' }} />;
}

// ─── Alert Document ───────────────────────────────────────────────────────────

function BreachAlertDocument({ breach, borrower, deal }: { breach: Breach; borrower: Borrower | undefined; deal: Deal | undefined }) {
  const deviation = breach.operator === '<=' ? breach.actualValue - breach.threshold : breach.threshold - breach.actualValue;
  const conf = Math.round(breach.agentConfidence * 100);
  const borderColor = breach.severity === 'Hard' ? '#dc2626' : '#f59e0b';
  const headerBg = breach.severity === 'Hard' ? '#fef2f2' : '#fffbeb';

  const distributedTo = [
    borrower?.loanOfficer ? `${borrower.loanOfficer} (Loan Officer)` : null,
    borrower?.relationshipManager ? `${borrower.relationshipManager} (Relationship Manager)` : null,
    'Compliance Team',
    borrower?.division ? `Deal Team — ${borrower.division}` : 'Deal Team',
  ].filter(Boolean) as string[];

  return (
    <div className="rounded-lg overflow-hidden"
      style={{ backgroundColor: '#fff', border: '1px solid #e2e8f0', borderTop: `4px solid ${borderColor}`, boxShadow: '0 1px 2px rgba(0,0,0,0.04)' }}>

      {/* Header */}
      <div className="px-8 py-5" style={{ backgroundColor: headerBg, borderBottom: '1px solid #e2e8f0' }}>
        <div className="flex items-start justify-between">
          <div>
            <div className="text-[10px] font-bold uppercase tracking-widest mb-1" style={{ color: '#94a3b8' }}>
              Covenant Breach Alert
            </div>
            <div className="text-lg font-bold" style={{ color: '#0f172a' }}>
              {breach.borrowerName} — {breach.covenantName}
            </div>
          </div>
          <div className="text-right">
            <SeverityBadge severity={breach.severity} size="md" />
            <div className="text-xs mt-1.5" style={{ color: '#94a3b8' }}>Generated by {breach.summaryAgent}</div>
            <div className="text-xs mt-0.5" style={{ color: '#94a3b8' }}>
              {fmtDate(breach.detectedDate)} · Confidence: {conf}%
            </div>
          </div>
        </div>
      </div>

      <div className="px-8 py-6">
        {/* Borrower & Deal */}
        <div className="grid grid-cols-2 gap-8">
          <div>
            <SectionLabel>Borrower</SectionLabel>
            <div className="text-base font-semibold" style={{ color: '#0f172a' }}>{breach.borrowerName}</div>
            {borrower && (
              <>
                <div className="text-sm mt-1" style={{ color: '#64748b' }}>{borrower.sector} · {borrower.division}</div>
                <div className="text-sm mt-0.5" style={{ color: '#64748b' }}>
                  RM: {borrower.relationshipManager} · LO: {borrower.loanOfficer}
                </div>
              </>
            )}
          </div>
          <div>
            <SectionLabel>Deal</SectionLabel>
            {deal ? (
              <>
                <div className="text-base font-semibold" style={{ color: '#0f172a' }}>
                  ${deal.amount}{deal.amountUnit} {deal.dealType}
                </div>
                <div className="text-sm mt-1" style={{ color: '#64748b' }}>
                  Originated: {fmtDateShort(deal.dealDate)} · Maturity: {fmtDateShort(deal.maturityDate)}
                </div>
                <div className="text-sm mt-0.5" style={{ color: '#64748b' }}>Law firm: {deal.lawFirm}</div>
              </>
            ) : (
              <div className="text-sm" style={{ color: '#94a3b8' }}>Deal details unavailable</div>
            )}
          </div>
        </div>

        <Divider />

        {/* Breach Details */}
        <SectionLabel>Breach Details</SectionLabel>
        <div className="grid grid-cols-2 gap-6">
          <div className="flex flex-col gap-3">
            <div>
              <div className="text-xs" style={{ color: '#94a3b8' }}>Covenant</div>
              <div className="text-sm font-medium mt-0.5" style={{ color: '#374151' }}>{breach.covenantName}</div>
            </div>
            <div>
              <div className="text-xs" style={{ color: '#94a3b8' }}>Threshold</div>
              <div className="text-sm font-semibold mt-0.5 tabular-nums" style={{ color: '#374151' }}>
                {operatorLabel(breach.operator)} {fmt(breach.threshold, breach.unit)}
              </div>
            </div>
            <div>
              <div className="text-xs" style={{ color: '#94a3b8' }}>Quarter</div>
              <div className="text-sm font-medium mt-0.5" style={{ color: '#374151' }}>{breach.quarter}</div>
            </div>
          </div>
          <div className="flex flex-col gap-3">
            <div>
              <div className="text-xs" style={{ color: '#94a3b8' }}>Actual Value</div>
              <div className="text-2xl font-bold tabular-nums mt-0.5" style={{ color: '#dc2626' }}>
                {fmt(breach.actualValue, breach.unit)}
              </div>
              <div className="text-xs mt-0.5" style={{ color: '#94a3b8' }}>
                Δ {fmt(Math.abs(deviation), breach.unit)} {breach.operator === '<=' ? 'above limit' : 'below minimum'}
              </div>
            </div>
            <div>
              <div className="text-xs" style={{ color: '#94a3b8' }}>Classification</div>
              <div className="flex items-center gap-2 mt-0.5">
                <SeverityBadge severity={breach.severity} />
                <span className="text-xs" style={{ color: breach.severity === 'Hard' ? '#dc2626' : '#b45309' }}>
                  {breach.severity === 'Hard' ? '→ Event of default' : '→ Discussion required'}
                </span>
              </div>
            </div>
          </div>
        </div>

        <Divider />

        {/* Borrower History */}
        <SectionLabel>Borrower History</SectionLabel>
        <BreachHistoryTimeline borrowerId={breach.borrowerId} />

        <Divider />

        {/* Sector Analysis */}
        <SectionLabel>Sector Analysis</SectionLabel>
        <div className="text-sm" style={{ color: '#374151' }}>{breach.sectorContext}</div>

        <Divider />

        {/* Recommended Action */}
        <SectionLabel>Recommended Action</SectionLabel>
        <div className="flex items-start gap-2 text-sm font-medium" style={{ color: '#374151' }}>
          <span style={{ color: '#3b82f6' }}>→</span>
          <span>{breach.recommendedAction}</span>
        </div>

        <Divider />

        {/* Agent Reasoning */}
        <SectionLabel>Agent Reasoning</SectionLabel>
        <BreachReasoningPanel breach={breach} />

        <Divider />

        {/* Distributed to */}
        <SectionLabel>Distributed To</SectionLabel>
        <div className="flex flex-col gap-1.5">
          {distributedTo.map((person, i) => (
            <div key={i} className="flex items-center gap-2 text-sm" style={{ color: '#374151' }}>
              <div className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ backgroundColor: '#94a3b8' }} />
              {person}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

function BreachSummaryContent() {
  const searchParams = useSearchParams();
  const paramBreachId = searchParams.get('breach');

  const allBreaches = useMemo(() => getBreaches(), []);

  const activeBreaches = useMemo(() =>
    allBreaches
      .filter(b => b.status !== 'Resolved — Waived')
      .sort((a, b) => {
        if (a.severity !== b.severity) return a.severity === 'Hard' ? -1 : 1;
        return new Date(b.detectedDate).getTime() - new Date(a.detectedDate).getTime();
      }),
    [allBreaches]
  );

  const [selectedId, setSelectedId] = useState<string>(() => {
    if (paramBreachId) return paramBreachId;
    const hardConfirmed = allBreaches
      .filter(b => b.severity === 'Hard' && b.status === 'Breach — Confirmed')
      .sort((a, b) => new Date(b.detectedDate).getTime() - new Date(a.detectedDate).getTime());
    return hardConfirmed[0]?.id ?? activeBreaches[0]?.id ?? '';
  });

  useEffect(() => {
    if (paramBreachId) setSelectedId(paramBreachId);
  }, [paramBreachId]);

  const breach = useMemo(() => allBreaches.find(b => b.id === selectedId), [allBreaches, selectedId]);
  const borrower = useMemo(() => breach ? getBorrowerById(breach.borrowerId) : undefined, [breach]);
  const deal = useMemo(() => breach ? getDealByBorrowerId(breach.borrowerId) : undefined, [breach]);

  return (
    <div className="max-w-[1400px] mx-auto">
      <PageHeader
        title="Breach Summary"
        description="AI-generated breach alert distributed to loan officer, RM, compliance, and deal team"
      />

      <div className="flex gap-6">
        {/* Left: selector + document */}
        <div className="flex-1 min-w-0">
          <div className="mb-4 flex items-center gap-3">
            <label className="text-xs font-semibold uppercase tracking-wider flex-shrink-0" style={{ color: '#94a3b8' }}>
              Breach
            </label>
            <select
              value={selectedId}
              onChange={e => setSelectedId(e.target.value)}
              className="text-sm px-3 py-1.5 rounded-md flex-1"
              style={{ border: '1px solid #e2e8f0', backgroundColor: '#fff', color: '#0f172a', outline: 'none', maxWidth: '480px' }}
            >
              {activeBreaches.map(b => (
                <option key={b.id} value={b.id}>
                  {b.borrowerName} — {b.covenantName} ({b.severity}) · {b.quarter}
                </option>
              ))}
            </select>
          </div>

          {breach ? (
            <BreachAlertDocument breach={breach} borrower={borrower} deal={deal} />
          ) : (
            <div className="text-sm" style={{ color: '#94a3b8' }}>No breach selected.</div>
          )}
        </div>

        {/* Right: action sidebar */}
        {breach && (
          <div className="flex flex-col gap-3" style={{ width: '192px', flexShrink: 0 }}>
            <div className="text-[10px] font-bold uppercase tracking-wider mb-1" style={{ color: '#94a3b8' }}>Actions</div>

            <Link href={`/waivers?breach=${breach.id}`}
              className="flex items-center justify-center px-4 py-2.5 rounded-lg text-sm font-medium"
              style={{ backgroundColor: '#f0fdf4', color: '#16a34a', border: '1px solid #bbf7d0' }}>
              Grant waiver →
            </Link>

            <button disabled
              className="flex items-center justify-center px-4 py-2.5 rounded-lg text-sm font-medium cursor-not-allowed"
              style={{ backgroundColor: '#f8fafc', color: '#94a3b8', border: '1px solid #e2e8f0' }}
              title="External workflow — out of scope for POC">
              Escalate further
            </button>

            <Link href={`/extraction?borrower=${breach.borrowerId}`}
              className="flex items-center justify-center px-4 py-2.5 rounded-lg text-sm font-medium"
              style={{ backgroundColor: '#f0f9ff', color: '#0369a1', border: '1px solid #bae6fd' }}>
              View covenants →
            </Link>

            <Link href="/breaches"
              className="flex items-center justify-center px-4 py-2.5 rounded-lg text-sm font-medium"
              style={{ backgroundColor: '#f8fafc', color: '#475569', border: '1px solid #e2e8f0' }}>
              ← All breaches
            </Link>

            {/* Quick stats */}
            <div className="mt-1 rounded-lg p-3" style={{ backgroundColor: '#f8fafc', border: '1px solid #e2e8f0' }}>
              <div className="text-[10px] font-bold uppercase tracking-wider mb-2" style={{ color: '#94a3b8' }}>Quick Stats</div>
              <div className="flex flex-col gap-1.5 text-xs">
                <div className="flex justify-between">
                  <span style={{ color: '#64748b' }}>Detected</span>
                  <span style={{ color: '#374151' }}>{fmtDate(breach.detectedDate)}</span>
                </div>
                <div className="flex justify-between">
                  <span style={{ color: '#64748b' }}>Quarter</span>
                  <span style={{ color: '#374151' }}>{breach.quarter}</span>
                </div>
                <div className="flex justify-between">
                  <span style={{ color: '#64748b' }}>Confidence</span>
                  <span style={{ color: '#374151' }}>{Math.round(breach.agentConfidence * 100)}%</span>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function BreachSummaryPage() {
  return (
    <Suspense fallback={null}>
      <BreachSummaryContent />
    </Suspense>
  );
}
